# Generated by Django 5.1.4 on 2025-01-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_address_customer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
