# Generated by Django 5.1.4 on 2025-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gallery', 'Gallery'), ('Outerwear', 'Outerwear'), ('Top', 'Top'), ('Bottom', 'Bottom'), ('ChicKicks', 'ChicKicks'), ('Accessories', 'Accessories')], max_length=11),
        ),
    ]
