# Generated by Django 5.1.4 on 2025-01-14 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('8f3a66dd-41c5-41c4-ab82-b3960d3c7765'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
