# Generated by Django 5.1.4 on 2025-01-15 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_shipping_address_alter_order_order_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('76d1e1ea-c6df-40c5-ab01-08ef31cd3114'), primary_key=True, serialize=False),
        ),
    ]
